# Generated by Django 5.0 on 2023-12-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
    ]
