# Generated by Django 5.0 on 2023-12-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0002_type_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('VideoID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('Video', models.FileField(upload_to='videos/')),
                ('Description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
