# Generated by Django 5.0 on 2023-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0003_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('GalleryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
            ],
        ),
        migrations.AlterField(
            model_name='shoesreviews',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
