# Generated by Django 5.0 on 2024-01-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0007_bestselling_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSImage',
            fields=[
                ('BSIID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
                ('BestSelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoesapp.bestselling', verbose_name='Best Selling Name')),
            ],
        ),
        migrations.CreateModel(
            name='DealsImage',
            fields=[
                ('DIID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
                ('Deals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoesapp.deals', verbose_name='Deals Name')),
            ],
        ),
    ]
